#!/usr/bin/env bash
# Guard: the repository must never carry COMSOL-derived data or copied
# documentation prose (docs/data-provenance.md). Run by CI on every push
# and PR; run locally before committing new fixtures:
#     bash scripts/check_no_derived_data.sh
set -euo pipefail
cd "$(dirname "$0")/.."

fail=0

# 1. Tracked files that are COMSOL model files, or products of the
#    scrapers/harvesters. `.gitignore` already excludes these, but that
#    only stops an accidental `git add` — a forced add would otherwise
#    reach a release. Models never belong in the tree: they are the
#    user's own work or COMSOL's, and neither is ours to redistribute.
derived_re='(^|/)(.*\.mph|.*\.mphbin|.*\.mphtxt|.*\.db|.*\.sqlite|.*\.db-(wal|shm|journal)|slots_dump\.jsonl|exemplars\.json|corpus_statistics\.json|mph_list\.txt)$|^corpus/(java|java_compiled)/'
if hits="$(git ls-files | grep -E "$derived_re" || true)"; [ -n "$hits" ]; then
    echo "ERROR: derived data is tracked (see docs/data-provenance.md):" >&2
    echo "$hits" | sed 's/^/  /' >&2
    fail=1
fi

# 2. Fixture files must not contain copied manual / Javadoc boilerplate.
#    The scraper fixtures are hand-authored in the real layout; the
#    markers below appear in every real page/PDF export and in no
#    hand-authored fixture.
copied_re='(Copyright|©|All rights reserved|COMSOL AB|COMSOL Multiphysics Reference|Generated by javadoc|JavaScript is disabled)'
if hits="$(git ls-files tests/fixtures/refmanual tests/fixtures/javadoc | xargs grep -lE "$copied_re" 2>/dev/null || true)"; [ -n "$hits" ]; then
    echo "ERROR: fixture looks copied from COMSOL documentation:" >&2
    echo "$hits" | sed 's/^/  /' >&2
    fail=1
fi

# 3. No site-specific strings anywhere in the tree: hostnames and
#    per-user home paths on either platform (`/data/home/<user>`,
#    `C:\Users\<user>`; write `%USERPROFILE%` / `~` in docs instead).
#    Only this script is exempt — it carries the patterns themselves.
site_re='(cfsenergy\.com|aws-flexlm|idea_apps|/data/home/[a-z0-9]+|[A-Za-z]:\\Users\\[A-Za-z0-9._-]+)'
if hits="$(git ls-files '*.py' '*.md' '*.java' '*.toml' '*.sh' '*.ps1' '*.yml' '*.json' \
        | grep -vE '^(scripts/check_no_derived_data\.sh)$' \
        | xargs grep -nE "$site_re" 2>/dev/null || true)"; [ -n "$hits" ]; then
    echo "ERROR: site-specific string in a tracked file (use an env var):" >&2
    echo "$hits" | cut -c1-140 | sed 's/^/  /' >&2
    fail=1
fi

if [ "$fail" -eq 0 ]; then
    echo "no derived data, copied doc prose, or site-specific strings tracked"
fi
exit "$fail"
